// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── WEB CONFIG (MERGED SUCCESSFULLY) ───────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuzBDA43c0p9Vb5flAA0O8J_6wVTuWQqo', 
    appId: '1:1097589089816:web:ea34e9f8b0e3ae57dfc56d', 
    messagingSenderId: '1097589089816',
    projectId: 'learning-navigator-ff142',
    authDomain: 'learning-navigator-ff142.firebaseapp.com',
    storageBucket: 'learning-navigator-ff142.firebasestorage.app',
  );

  // ─── ANDROID CONFIG ──────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExke1exUVU4mbFXVCPUC3VKOUrqv85HM',
    appId: '1:1097589089816:android:af352f8061db73eddfc56d',
    messagingSenderId: '1097589089816',
    projectId: 'learning-navigator-ff142',
    storageBucket: 'learning-navigator-ff142.firebasestorage.app',
  );
}