// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_OTXlENNYW27VzcAe-2AUueF8IesM0Es',
    appId: '1:925029200593:web:d1e4746ee8f6212aa4cbf0',
    messagingSenderId: '925029200593',
    projectId: 'learningnavigatorapp',
    authDomain: 'learningnavigatorapp.firebaseapp.com',
    storageBucket: 'learningnavigatorapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe2NZd-9HnWi5qUabGVW93ssYemMFeYL8',
    appId: '1:925029200593:android:204e08b24356a2dda4cbf0',
    messagingSenderId: '925029200593',
    projectId: 'learningnavigatorapp',
    storageBucket: 'learningnavigatorapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCba-LcXsqQmVaRWWefO4baIDQ_IAMQO98',
    appId: '1:925029200593:ios:0ae13bd87c10efe9a4cbf0',
    messagingSenderId: '925029200593',
    projectId: 'learningnavigatorapp',
    storageBucket: 'learningnavigatorapp.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCba-LcXsqQmVaRWWefO4baIDQ_IAMQO98',
    appId: '1:925029200593:ios:0ae13bd87c10efe9a4cbf0',
    messagingSenderId: '925029200593',
    projectId: 'learningnavigatorapp',
    storageBucket: 'learningnavigatorapp.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_OTXlENNYW27VzcAe-2AUueF8IesM0Es',
    appId: '1:925029200593:web:a52d315c4e1e23c0a4cbf0',
    messagingSenderId: '925029200593',
    projectId: 'learningnavigatorapp',
    authDomain: 'learningnavigatorapp.firebaseapp.com',
    storageBucket: 'learningnavigatorapp.firebasestorage.app',
  );
}
